Cloud testapp
Otus-DevOps-2021-11/gbutyaev_infra pull request #3
Opened 2022-01-13 13:11 UTC by gbutyaev

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - У себя на хосте установил и инициализировал клиент для YC
 - Создал профиль для YC
 - Создал новый инстанс c помощью клиента для YC и подключился к нему
 - Установил ruby, mogodb, bundler
 - Инициализировал git и склонировал репозиторий приложения reddit, после чего его установил
 - Создал скрипты deploy.sh, install_mongodb.sh, install_ruby.sh

## Как проверить работоспособность:
 - Перейти по ссылке http://84.201.128.214:9292/

## PR checklist
- [x] Выставил label с темой домашнего задания

2022-01-13 13:14 UTC, gbutyaev commented
Здравствуйте, все сделал. Посмотрите, пожалуйста, похоже проблема опять в самих тестах

2022-01-13 13:42 UTC, mrgreyves requested changes
Здравствуйте!)
Проблема тут не в тестах
Часть файлов не исполняемые, это нужно пофиксить

2022-01-13 14:54 UTC, gbutyaev commented
Странно, моей домашней директории они  и так были исполняемые, но попробовал дать права через 
```
 git update-index --chmod=+x deploy.sh install_ruby.sh install_mongodb.sh
```
вроде стало получше)

2022-01-14 13:50 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, вот сейчас норм, с монгой порой в тестах бывают такие приколы =)
Апрув =)

2022-01-14 14:17 UTC, merged